export default [
  {
    "login": "nayakashutosh9",
    "id": 43809818,
    "node_id": "MDQ6VXNlcjQzODA5ODE4",
    "avatar_url": "https://avatars2.githubusercontent.com/u/43809818?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nayakashutosh9",
    "html_url": "https://github.com/nayakashutosh9",
    "followers_url": "https://api.github.com/users/nayakashutosh9/followers",
    "following_url": "https://api.github.com/users/nayakashutosh9/following{/other_user}",
    "gists_url": "https://api.github.com/users/nayakashutosh9/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nayakashutosh9/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nayakashutosh9/subscriptions",
    "organizations_url": "https://api.github.com/users/nayakashutosh9/orgs",
    "repos_url": "https://api.github.com/users/nayakashutosh9/repos",
    "events_url": "https://api.github.com/users/nayakashutosh9/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nayakashutosh9/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "tts89",
    "id": 53234601,
    "node_id": "MDQ6VXNlcjUzMjM0NjAx",
    "avatar_url": "https://avatars1.githubusercontent.com/u/53234601?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tts89",
    "html_url": "https://github.com/tts89",
    "followers_url": "https://api.github.com/users/tts89/followers",
    "following_url": "https://api.github.com/users/tts89/following{/other_user}",
    "gists_url": "https://api.github.com/users/tts89/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tts89/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tts89/subscriptions",
    "organizations_url": "https://api.github.com/users/tts89/orgs",
    "repos_url": "https://api.github.com/users/tts89/repos",
    "events_url": "https://api.github.com/users/tts89/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tts89/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "prady12345",
    "id": 43078446,
    "node_id": "MDQ6VXNlcjQzMDc4NDQ2",
    "avatar_url": "https://avatars3.githubusercontent.com/u/43078446?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/prady12345",
    "html_url": "https://github.com/prady12345",
    "followers_url": "https://api.github.com/users/prady12345/followers",
    "following_url": "https://api.github.com/users/prady12345/following{/other_user}",
    "gists_url": "https://api.github.com/users/prady12345/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/prady12345/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/prady12345/subscriptions",
    "organizations_url": "https://api.github.com/users/prady12345/orgs",
    "repos_url": "https://api.github.com/users/prady12345/repos",
    "events_url": "https://api.github.com/users/prady12345/events{/privacy}",
    "received_events_url": "https://api.github.com/users/prady12345/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "soulsam480",
    "id": 35460828,
    "node_id": "MDQ6VXNlcjM1NDYwODI4",
    "avatar_url": "https://avatars3.githubusercontent.com/u/35460828?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/soulsam480",
    "html_url": "https://github.com/soulsam480",
    "followers_url": "https://api.github.com/users/soulsam480/followers",
    "following_url": "https://api.github.com/users/soulsam480/following{/other_user}",
    "gists_url": "https://api.github.com/users/soulsam480/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/soulsam480/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/soulsam480/subscriptions",
    "organizations_url": "https://api.github.com/users/soulsam480/orgs",
    "repos_url": "https://api.github.com/users/soulsam480/repos",
    "events_url": "https://api.github.com/users/soulsam480/events{/privacy}",
    "received_events_url": "https://api.github.com/users/soulsam480/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Mrutyunjay01",
    "id": 53314831,
    "node_id": "MDQ6VXNlcjUzMzE0ODMx",
    "avatar_url": "https://avatars2.githubusercontent.com/u/53314831?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Mrutyunjay01",
    "html_url": "https://github.com/Mrutyunjay01",
    "followers_url": "https://api.github.com/users/Mrutyunjay01/followers",
    "following_url": "https://api.github.com/users/Mrutyunjay01/following{/other_user}",
    "gists_url": "https://api.github.com/users/Mrutyunjay01/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Mrutyunjay01/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Mrutyunjay01/subscriptions",
    "organizations_url": "https://api.github.com/users/Mrutyunjay01/orgs",
    "repos_url": "https://api.github.com/users/Mrutyunjay01/repos",
    "events_url": "https://api.github.com/users/Mrutyunjay01/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Mrutyunjay01/received_events",
    "type": "User",
    "site_admin": false
  }
];
