export default {
  "login": "Sushil211",
  "id": 54482089,
  "node_id": "MDQ6VXNlcjU0NDgyMDg5",
  "avatar_url": "https://avatars1.githubusercontent.com/u/54482089?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Sushil211",
  "html_url": "https://github.com/Sushil211",
  "followers_url": "https://api.github.com/users/Sushil211/followers",
  "following_url": "https://api.github.com/users/Sushil211/following{/other_user}",
  "gists_url": "https://api.github.com/users/Sushil211/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Sushil211/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Sushil211/subscriptions",
  "organizations_url": "https://api.github.com/users/Sushil211/orgs",
  "repos_url": "https://api.github.com/users/Sushil211/repos",
  "events_url": "https://api.github.com/users/Sushil211/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Sushil211/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sushil Sekhar Satapathy",
  "company": "National Institute of Technology, Rourkela",
  "blog": "https://www.linkedin.com/in/sushil-sekhar-satapathy-78ab181a4/",
  "location": "Bhubaneswar, Odisha, India",
  "email": null,
  "hireable": true,
  "bio": "Developer | Competitive Programmer | Chess Enthusiast",
  "twitter_username": null,
  "public_repos": 15,
  "public_gists": 0,
  "followers": 5,
  "following": 6,
  "created_at": "2019-08-24T18:19:17Z",
  "updated_at": "2020-10-15T05:25:53Z"
};
